// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/thwqsz/uptime-monitor/internal/models"
)

// CheckLogRepository is an autogenerated mock type for the CheckLogRepository type
type CheckLogRepository struct {
	mock.Mock
}

// CreateCheckLog provides a mock function with given fields: ctx, log
func (_m *CheckLogRepository) CreateCheckLog(ctx context.Context, log *models.CheckLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CheckLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCheckLogRepository creates a new instance of CheckLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckLogRepository {
	mock := &CheckLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
