// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	checker "github.com/thwqsz/uptime-monitor/internal/checker"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Checker is an autogenerated mock type for the Checker type
type Checker struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx, url, timeout
func (_m *Checker) Check(ctx context.Context, url string, timeout time.Duration) (*checker.CheckResponse, error) {
	ret := _m.Called(ctx, url, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 *checker.CheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (*checker.CheckResponse, error)); ok {
		return rf(ctx, url, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) *checker.CheckResponse); ok {
		r0 = rf(ctx, url, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*checker.CheckResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, url, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewChecker creates a new instance of Checker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Checker {
	mock := &Checker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
