// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/thwqsz/uptime-monitor/internal/models"
)

// GetAllTargeter is an autogenerated mock type for the GetAllTargeter type
type GetAllTargeter struct {
	mock.Mock
}

// GetAllTargets provides a mock function with given fields: ctx
func (_m *GetAllTargeter) GetAllTargets(ctx context.Context) ([]*models.Target, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTargets")
	}

	var r0 []*models.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Target, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Target); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetAllTargeter creates a new instance of GetAllTargeter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetAllTargeter(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetAllTargeter {
	mock := &GetAllTargeter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
