// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/thwqsz/uptime-monitor/internal/models"
)

// SchedulerControl is an autogenerated mock type for the SchedulerControl type
type SchedulerControl struct {
	mock.Mock
}

// StartTarget provides a mock function with given fields: target
func (_m *SchedulerControl) StartTarget(target *models.Target) {
	_m.Called(target)
}

// StopTarget provides a mock function with given fields: targetID
func (_m *SchedulerControl) StopTarget(targetID int64) {
	_m.Called(targetID)
}

// NewSchedulerControl creates a new instance of SchedulerControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerControl {
	mock := &SchedulerControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
