// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/thwqsz/uptime-monitor/internal/models"
)

// TargetChecker is an autogenerated mock type for the TargetChecker type
type TargetChecker struct {
	mock.Mock
}

// CheckTargetSystem provides a mock function with given fields: ctx, targetID
func (_m *TargetChecker) CheckTargetSystem(ctx context.Context, targetID int64) (*models.CheckLog, error) {
	ret := _m.Called(ctx, targetID)

	if len(ret) == 0 {
		panic("no return value specified for CheckTargetSystem")
	}

	var r0 *models.CheckLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.CheckLog, error)); ok {
		return rf(ctx, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.CheckLog); ok {
		r0 = rf(ctx, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CheckLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTargetChecker creates a new instance of TargetChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTargetChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *TargetChecker {
	mock := &TargetChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
