// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/thwqsz/uptime-monitor/internal/models"
)

// TargetRepository is an autogenerated mock type for the TargetRepository type
type TargetRepository struct {
	mock.Mock
}

// CreateTarget provides a mock function with given fields: ctx, target
func (_m *TargetRepository) CreateTarget(ctx context.Context, target *models.Target) error {
	ret := _m.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for CreateTarget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Target) error); ok {
		r0 = rf(ctx, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTarget provides a mock function with given fields: ctx, targetID, userID
func (_m *TargetRepository) DeleteTarget(ctx context.Context, targetID int64, userID int64) (int64, error) {
	ret := _m.Called(ctx, targetID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTarget")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return rf(ctx, targetID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = rf(ctx, targetID, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, targetID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTargets provides a mock function with given fields: ctx
func (_m *TargetRepository) GetAllTargets(ctx context.Context) ([]*models.Target, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTargets")
	}

	var r0 []*models.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Target, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Target); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTargetByID provides a mock function with given fields: ctx, targetID
func (_m *TargetRepository) GetTargetByID(ctx context.Context, targetID int64) (*models.Target, error) {
	ret := _m.Called(ctx, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetTargetByID")
	}

	var r0 *models.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Target, error)); ok {
		return rf(ctx, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Target); ok {
		r0 = rf(ctx, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTargetsByUserID provides a mock function with given fields: ctx, userID
func (_m *TargetRepository) GetTargetsByUserID(ctx context.Context, userID int64) ([]*models.Target, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTargetsByUserID")
	}

	var r0 []*models.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*models.Target, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.Target); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTargetRepository creates a new instance of TargetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTargetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TargetRepository {
	mock := &TargetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
