// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/checkerpb/checker.proto

package checkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	TimeoutSec    int32                  `protobuf:"varint,2,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_internal_grpc_checkerpb_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_checkerpb_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_checkerpb_checker_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CheckRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type CheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ResponseTimeMs int32                  `protobuf:"varint,2,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	ErrMsg         string                 `protobuf:"bytes,3,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	StatusCode     int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_internal_grpc_checkerpb_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_checkerpb_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_checkerpb_checker_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckResponse) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *CheckResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *CheckResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_internal_grpc_checkerpb_checker_proto protoreflect.FileDescriptor

const file_internal_grpc_checkerpb_checker_proto_rawDesc = "" +
	"\n" +
	"%internal/grpc/checkerpb/checker.proto\x12\tcheckerpb\"A\n" +
	"\fCheckRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\vtimeout_sec\x18\x02 \x01(\x05R\n" +
	"timeoutSec\"\x8b\x01\n" +
	"\rCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12(\n" +
	"\x10response_time_ms\x18\x02 \x01(\x05R\x0eresponseTimeMs\x12\x17\n" +
	"\aerr_msg\x18\x03 \x01(\tR\x06errMsg\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode2L\n" +
	"\x0eCheckerService\x12:\n" +
	"\x05Check\x12\x17.checkerpb.CheckRequest\x1a\x18.checkerpb.CheckResponseB:Z8github.com/thwqsz/uptime-monitor/internal/grpc/checkerpbb\x06proto3"

var (
	file_internal_grpc_checkerpb_checker_proto_rawDescOnce sync.Once
	file_internal_grpc_checkerpb_checker_proto_rawDescData []byte
)

func file_internal_grpc_checkerpb_checker_proto_rawDescGZIP() []byte {
	file_internal_grpc_checkerpb_checker_proto_rawDescOnce.Do(func() {
		file_internal_grpc_checkerpb_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_checkerpb_checker_proto_rawDesc), len(file_internal_grpc_checkerpb_checker_proto_rawDesc)))
	})
	return file_internal_grpc_checkerpb_checker_proto_rawDescData
}

var file_internal_grpc_checkerpb_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_checkerpb_checker_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: checkerpb.CheckRequest
	(*CheckResponse)(nil), // 1: checkerpb.CheckResponse
}
var file_internal_grpc_checkerpb_checker_proto_depIdxs = []int32{
	0, // 0: checkerpb.CheckerService.Check:input_type -> checkerpb.CheckRequest
	1, // 1: checkerpb.CheckerService.Check:output_type -> checkerpb.CheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_checkerpb_checker_proto_init() }
func file_internal_grpc_checkerpb_checker_proto_init() {
	if File_internal_grpc_checkerpb_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_checkerpb_checker_proto_rawDesc), len(file_internal_grpc_checkerpb_checker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_checkerpb_checker_proto_goTypes,
		DependencyIndexes: file_internal_grpc_checkerpb_checker_proto_depIdxs,
		MessageInfos:      file_internal_grpc_checkerpb_checker_proto_msgTypes,
	}.Build()
	File_internal_grpc_checkerpb_checker_proto = out.File
	file_internal_grpc_checkerpb_checker_proto_goTypes = nil
	file_internal_grpc_checkerpb_checker_proto_depIdxs = nil
}
